/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BreakdownRouteImport } from './routes/breakdown'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as KontenRouteImport } from './routes/konten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TugasRouteImport } from './routes/tugas'
import { Route as UsersRouteImport } from './routes/users'
import { Route as KontenIdRouteImport } from './routes/konten.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakdownRoute = BreakdownRouteImport.update({
  id: '/breakdown',
  path: '/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const KontenRoute = KontenRouteImport.update({
  id: '/konten',
  path: '/konten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TugasRoute = TugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const KontenIdRoute = KontenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KontenRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breakdown': typeof BreakdownRoute
  '/crm': typeof CrmRoute
  '/daftar': typeof DaftarRoute
  '/forbidden': typeof ForbiddenRoute
  '/konten': typeof KontenRouteWithChildren
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/panduan': typeof PanduanRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/tugas': typeof TugasRoute
  '/users': typeof UsersRoute
  '/konten/$id': typeof KontenIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breakdown': typeof BreakdownRoute
  '/crm': typeof CrmRoute
  '/daftar': typeof DaftarRoute
  '/forbidden': typeof ForbiddenRoute
  '/konten': typeof KontenRouteWithChildren
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/panduan': typeof PanduanRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/tugas': typeof TugasRoute
  '/users': typeof UsersRoute
  '/konten/$id': typeof KontenIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breakdown': typeof BreakdownRoute
  '/crm': typeof CrmRoute
  '/daftar': typeof DaftarRoute
  '/forbidden': typeof ForbiddenRoute
  '/konten': typeof KontenRouteWithChildren
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/panduan': typeof PanduanRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/tugas': typeof TugasRoute
  '/users': typeof UsersRoute
  '/konten/$id': typeof KontenIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breakdown'
    | '/crm'
    | '/daftar'
    | '/forbidden'
    | '/konten'
    | '/login'
    | '/lupa-password'
    | '/onboarding'
    | '/panduan'
    | '/ranking'
    | '/reset-password'
    | '/settings'
    | '/tugas'
    | '/users'
    | '/konten/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breakdown'
    | '/crm'
    | '/daftar'
    | '/forbidden'
    | '/konten'
    | '/login'
    | '/lupa-password'
    | '/onboarding'
    | '/panduan'
    | '/ranking'
    | '/reset-password'
    | '/settings'
    | '/tugas'
    | '/users'
    | '/konten/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/breakdown'
    | '/crm'
    | '/daftar'
    | '/forbidden'
    | '/konten'
    | '/login'
    | '/lupa-password'
    | '/onboarding'
    | '/panduan'
    | '/ranking'
    | '/reset-password'
    | '/settings'
    | '/tugas'
    | '/users'
    | '/konten/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreakdownRoute: typeof BreakdownRoute
  CrmRoute: typeof CrmRoute
  DaftarRoute: typeof DaftarRoute
  ForbiddenRoute: typeof ForbiddenRoute
  KontenRoute: typeof KontenRouteWithChildren
  LoginRoute: typeof LoginRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  PanduanRoute: typeof PanduanRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TugasRoute: typeof TugasRoute
  UsersRoute: typeof UsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakdown': {
      id: '/breakdown'
      path: '/breakdown'
      fullPath: '/breakdown'
      preLoaderRoute: typeof BreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konten': {
      id: '/konten'
      path: '/konten'
      fullPath: '/konten'
      preLoaderRoute: typeof KontenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tugas': {
      id: '/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof TugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konten/$id': {
      id: '/konten/$id'
      path: '/$id'
      fullPath: '/konten/$id'
      preLoaderRoute: typeof KontenIdRouteImport
      parentRoute: typeof KontenRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KontenRouteChildren {
  KontenIdRoute: typeof KontenIdRoute
}

const KontenRouteChildren: KontenRouteChildren = {
  KontenIdRoute: KontenIdRoute,
}

const KontenRouteWithChildren =
  KontenRoute._addFileChildren(KontenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreakdownRoute: BreakdownRoute,
  CrmRoute: CrmRoute,
  DaftarRoute: DaftarRoute,
  ForbiddenRoute: ForbiddenRoute,
  KontenRoute: KontenRouteWithChildren,
  LoginRoute: LoginRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  PanduanRoute: PanduanRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TugasRoute: TugasRoute,
  UsersRoute: UsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
